import type { Metadata } from 'next';
import { Inter, Roboto } from 'next/font/google';
import './globals.css';

//context
import { ThemeProvider } from '@shared/context/theme-provider';

const inter = Inter({
    variable: '--font-inter',
    weight: ['400', '500', '700'],
    subsets: ['latin'],
});

const roboto = Roboto({
    variable: '--font-roboto',
    weight: ['400', '500', '700'],
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-BR" suppressHydrationWarning>
            <body
                className={`${inter.variable} ${roboto.variable} antialiased`}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
